apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: http-server
  namespace: home-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: server
          image: 1cylon1/http-server:0.0.2
          ports:
            - containerPort: 8080
              name: web

